package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"sync"

	"github.com/hypoballad/virgil/internal/repository"
	"github.com/hypoballad/virgil/internal/shadow"
)

// Registry はツールの登録と取得を管理する
type Registry struct {
	mu                 sync.RWMutex
	tools              map[string]Tool
	workspaceRoot      string
	editDenylist       []string
	editDenylistSource string
}

// NewRegistry は新しいレジストリを作成
func NewRegistry() *Registry {
	return &Registry{
		tools: make(map[string]Tool),
	}
}

// Register はツールを登録
func (r *Registry) Register(tool Tool) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	name := tool.Name()
	if _, exists := r.tools[name]; exists {
		return fmt.Errorf("tool %q already registered", name)
	}

	r.tools[name] = tool
	return nil
}

// SetEditDenylist blocks mutating path-based tools for the given workspace paths.
// Empty paths disable the denylist restriction.
func (r *Registry) SetEditDenylist(workspaceRoot string, paths []string, source string) {
	r.mu.Lock()
	defer r.mu.Unlock()

	r.workspaceRoot = filepath.Clean(workspaceRoot)
	r.editDenylist = normalizePolicyPaths(r.workspaceRoot, paths)
	r.editDenylistSource = strings.TrimSpace(source)
}

// Get は名前でツールを取得
func (r *Registry) Get(name string) (Tool, bool) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	tool, exists := r.tools[name]
	return tool, exists
}

// Definitions は全ツールの定義をLLM用に取得
func (r *Registry) Definitions() []ToolDefinition {
	r.mu.RLock()
	defer r.mu.RUnlock()

	defs := make([]ToolDefinition, 0, len(r.tools))
	for _, tool := range r.tools {
		defs = append(defs, tool.Definition())
	}
	return defs
}

// Execute は指定された名前のツールを実行
func (r *Registry) Execute(ctx context.Context, name string, args json.RawMessage) (*Result, error) {
	tool, exists := r.Get(name)
	if !exists {
		return nil, fmt.Errorf("tool %q not found", name)
	}
	if blockMsg := r.mutationPathDenylistBlock(tool, args); blockMsg != "" {
		return ErrorResult(blockMsg), nil
	}

	return tool.Execute(ctx, args)
}

func (r *Registry) mutationPathDenylistBlock(tool Tool, args json.RawMessage) string {
	if !tool.IsMutating() {
		return ""
	}

	r.mu.RLock()
	workspaceRoot := r.workspaceRoot
	denylist := append([]string(nil), r.editDenylist...)
	source := r.editDenylistSource
	r.mu.RUnlock()

	if len(denylist) == 0 {
		return ""
	}

	var parsed struct {
		Path string `json:"path"`
	}
	if err := json.Unmarshal(args, &parsed); err != nil || strings.TrimSpace(parsed.Path) == "" {
		return fmt.Sprintf("Tool %q blocked: mutating tool call must include a path when edit ignorelist is active.", tool.Name())
	}
	if !pathDeniedByPolicy(workspaceRoot, parsed.Path, denylist) {
		return ""
	}
	if source == "" {
		source = "edit ignorelist"
	}
	return fmt.Sprintf(
		"Tool %q blocked by %s: path %q matches ignored edit paths: %s. "+
			"Do not edit this file; report the needed change and ask for explicit permission.",
		tool.Name(), source, parsed.Path, strings.Join(denylist, ", "),
	)
}

func normalizePolicyPaths(workspaceRoot string, paths []string) []string {
	out := make([]string, 0, len(paths))
	seen := map[string]bool{}
	for _, path := range paths {
		normalized := normalizePolicyPath(workspaceRoot, path)
		if normalized == "" || seen[normalized] {
			continue
		}
		seen[normalized] = true
		out = append(out, normalized)
	}
	return out
}

func normalizePolicyPath(workspaceRoot string, path string) string {
	path = strings.TrimSpace(path)
	if path == "" {
		return ""
	}
	dirPattern := strings.HasSuffix(path, "/") || strings.HasSuffix(path, string(filepath.Separator))
	if filepath.IsAbs(path) && strings.TrimSpace(workspaceRoot) != "" {
		rel, err := filepath.Rel(filepath.Clean(workspaceRoot), filepath.Clean(path))
		if err != nil || rel == "." || strings.HasPrefix(rel, "../") || rel == ".." {
			return ""
		}
		path = rel
	}
	path = filepath.ToSlash(filepath.Clean(path))
	path = strings.TrimPrefix(path, "./")
	if path == "." || strings.HasPrefix(path, "../") || path == ".." {
		return ""
	}
	if dirPattern && !strings.HasSuffix(path, "/") {
		path += "/"
	}
	return path
}

func pathDeniedByPolicy(workspaceRoot string, path string, denylist []string) bool {
	rel := normalizeMutatingPathForPolicy(workspaceRoot, path)
	if rel == "" {
		return false
	}
	for _, denied := range denylist {
		if strings.HasSuffix(denied, "/") {
			prefix := strings.TrimSuffix(denied, "/")
			if rel == prefix || strings.HasPrefix(rel, denied) {
				return true
			}
			continue
		}
		if rel == denied {
			return true
		}
	}
	return false
}

func normalizeMutatingPathForPolicy(workspaceRoot string, path string) string {
	path = strings.TrimSpace(path)
	if path == "" {
		return ""
	}
	var abs string
	if filepath.IsAbs(path) {
		abs = filepath.Clean(path)
	} else if strings.TrimSpace(workspaceRoot) != "" {
		abs = filepath.Join(workspaceRoot, path)
	} else {
		return normalizePolicyPath("", path)
	}
	if strings.TrimSpace(workspaceRoot) == "" {
		return filepath.ToSlash(filepath.Clean(abs))
	}
	root := filepath.Clean(workspaceRoot)
	rel, err := filepath.Rel(root, abs)
	if err != nil {
		return ""
	}
	rel = filepath.ToSlash(filepath.Clean(rel))
	if rel == "." || strings.HasPrefix(rel, "../") || rel == ".." {
		return ""
	}
	return rel
}

// RegisterRunCommand は run_command ツールを登録する
func (r *Registry) RegisterRunCommand(config RunCommandConfig) {
	r.Register(NewRunCommandTool(config))
}

// RegisterGetFileOutline は get_file_outline ツールを登録する
func (r *Registry) RegisterGetFileOutline(workspaceRoot string) {
	r.Register(NewGetFileOutlineTool(workspaceRoot))
}

// RegisterReadSymbol は read_symbol ツールを登録する
func (r *Registry) RegisterReadSymbol(workspaceRoot string) {
	r.Register(NewReadSymbolTool(workspaceRoot))
}

// RegisterGetSymbolOutline は get_symbol_outline ツールを登録する
func (r *Registry) RegisterGetSymbolOutline(workspaceRoot string) {
	r.Register(NewGetSymbolOutlineTool(workspaceRoot))
}

// RegisterEditWithPattern は edit_with_pattern ツールを登録する
func (r *Registry) RegisterEditWithPattern(workspaceRoot string) {
	r.Register(NewEditWithPatternTool(workspaceRoot))
}

// RegisterFetchDocs は fetch_docs ツールを登録する
func (r *Registry) RegisterFetchDocs() {
	r.Register(NewFetchDocsTool())
}

// RegisterRunTests は run_tests ツールを登録する
func (r *Registry) RegisterRunTests(workspaceRoot string) {
	r.Register(NewRunTestsTool(workspaceRoot))
}

func (r *Registry) RegisterCheckSyntaxTools(workspaceRoot string) {
	r.Register(NewCheckPythonSyntaxTool(workspaceRoot))
	r.Register(NewCheckGoPackageTool(workspaceRoot))
	r.Register(NewCheckJavaScriptSyntaxTool(workspaceRoot))
	r.Register(NewCheckTypeScriptTool(workspaceRoot))
}

// RegisterGetCallers は get_callers ツールを登録する
func (r *Registry) RegisterGetCallers(calls *repository.CallRepository) {
	r.Register(NewGetCallersTool(calls))
}

// RegisterGetCallGraph は get_call_graph ツールを登録する
func (r *Registry) RegisterGetCallGraph(calls *repository.CallRepository) {
	r.Register(NewGetCallGraphTool(calls))
}

// RegisterGetFileImports は get_file_imports ツールを登録する
func (r *Registry) RegisterGetFileImports(workspaceRoot string, imports *repository.ImportRepository, symbols *repository.SymbolRepository) {
	r.Register(NewGetFileImportsTool(workspaceRoot, imports, symbols))
}

// RegisterGetJSONOutline は get_json_outline ツールを登録する
func (r *Registry) RegisterGetJSONOutline(workspaceRoot string) {
	r.Register(NewGetJSONOutlineTool(workspaceRoot))
}

// RegisterReadJSONPath は read_json_path ツールを登録する
func (r *Registry) RegisterReadJSONPath(workspaceRoot string) {
	r.Register(NewReadJSONPathTool(workspaceRoot))
}

func (r *Registry) RegisterGetMarkdownOutline(workspaceRoot string) {
	r.Register(NewGetMarkdownOutlineTool(workspaceRoot))
}

func (r *Registry) RegisterReadMarkdownSection(workspaceRoot string) {
	r.Register(NewReadMarkdownSectionTool(workspaceRoot))
}

// RegisterFindDependents は find_dependents ツールを登録する
func (r *Registry) RegisterFindDependents(imports *repository.ImportRepository) {
	r.Register(NewFindDependentsTool(imports))
}

// RegisterGetDiffSummary は get_diff_summary ツールを登録する。
func (r *Registry) RegisterGetDiffSummary(shadowRepo *shadow.ShadowRepo) {
	r.Register(NewGetDiffSummaryTool(shadowRepo))
}
